server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amiturfriend007/avengersFinal
          repos:

            staging-properties-repo:
              pattern : config-client/staging
              uri: https://github.com/amiturfriend007/avengersFinal
              search-paths:
                - config-externalization/environment

            prod-properies-repo:
              uri: https://github.com/amiturfriend007/avengersFinal
              pattern: config-client/prod
              search-paths:
                - config-externalization/environment/{profile}

            any-request-repo:
              uri: https://github.com/amiturfriend007/avengersFinal
              pattern: config-client*/*
              search-paths:
                - config-externalization/environment/{application}/{profile}
